//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test100Hours3
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public string ContactID { get; set; }
        public string ContactStatus { get; set; }
        public string DateLastUpdated { get; set; }
        public string DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Organization { get; set; }
        public string RelationshipType { get; set; }
        public string ContactType { get; set; }
        public string JobTitle { get; set; }
        public string JobFunction { get; set; }
        public string DoNotContact { get; set; }
        public string OptedInEmail { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string OtherSocialProfiles { get; set; }
        public string LinkedinProfile { get; set; }
        public string ContactName { get; set; }
    }
}
